language: node_js
node_js:
  - "node"
cache:
  directories:
    - ~/.npm
script:
- npm test || true
notifications:
  email: false
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
